name: WinServe

on: [push]

jobs:
  Dotnet-Core:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build with dotnet
      run: dotnet publish -c Release
    - name: Inno setup
      run: ISCC.exe ./Setup/winserve.iss

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./Setup/Output/mysetup.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
